plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Your awesome title
author: GitHub User
author_url: /about/
email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true
excerpt_separator: <!--more-->
#paginate: 5 # Uncomment this to list posts on multiple pages

# social links
twitter_username: jekyllrb
github_username:  jekyll
# rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com



# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: jekyll-theme-antisocial
exclude:
  - CODE_OF_CONDUCT.md
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-antisocial.gemspec
  - LICENSE.txt
